/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectol;

import conexion.ConexBD;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author EDUARD
 */
public class FrmTablaDatos extends javax.swing.JFrame {

    /**
     * Creates new form FrmTablaDatos
     */
    ConexBD cnx = new ConexBD();
    Connection con = cnx.Conectar();
    public String dato;
    public FrmTablaDatos() {
        initComponents();
        mostrarDatos();
    }
    
    public void mostrarDatos(){
        
        String[] titulos = {"Id", "Nombre", "Primer Apellido", "Segundo Apellido",
            "Tipo de Documento", "Numero de Documento", "Email", "Numero Celular", "Codigo"};
        String[] registros = new String[9];
        
        DefaultTableModel modelo =  new DefaultTableModel(null, titulos);
        //String SQL = "select * from tblempleado";
        
        
        try{
            CallableStatement consulta = con.prepareCall("{call consulta_empleados}");
//            Statement st = con.createStatement();
            ResultSet rs = consulta.executeQuery();
            
            while(rs.next()){
                registros[0] = rs.getString("id");
                registros[1] = rs.getString("nombre");
                registros[2] = rs.getString("apellido1");
                registros[3] = rs.getString("apellido2");
                registros[4] = rs.getString("tipo_documento");
                registros[5] = rs.getString("numero_documento");
                registros[6] = rs.getString("email");
                registros[7] = rs.getString("numero_celular");
                registros[8] = rs.getString("codigo");
                
                modelo.addRow(registros);
            }
            DataTable.setModel(modelo);
            rs.close();
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,"Error " + e.getMessage());
        } 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        DataTable = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        txtBuscar = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Empleados");

        DataTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        DataTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DataTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(DataTable);

        jLabel2.setText("N° de Documento");

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 606, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnBuscar)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(268, 268, 268)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar))
                .addGap(24, 24, 24)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DataTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DataTableMouseClicked
//        seleccion = DataTable.rowAtPoint(evt.getPoint());
//        System.out.println(seleccion);
        DefaultTableModel tm = (DefaultTableModel) DataTable.getModel();
        dato=String.valueOf(tm.getValueAt(DataTable.getSelectedRow(),0));
        System.out.println(dato);
        FrmTarjetaEmpleado frmEmpleado = new FrmTarjetaEmpleado(dato);
        frmEmpleado.setVisible(true);
    }//GEN-LAST:event_DataTableMouseClicked

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        try {
            if (txtBuscar.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "¡Cuidado! " + " No has ingresado ningun dato");
                mostrarDatos();
            } else {
                mostrarEmpleado();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,"Error " + e.getMessage());
        }

    }//GEN-LAST:event_btnBuscarActionPerformed

    public void mostrarEmpleado(){
         String[] titulos = {"Id", "Nombre", "Primer Apellido", "Segundo Apellido",
            "Tipo de Documento", "Numero de Documento", "Email", "Numero Celular", "Codigo"};
        String[] registros = new String[9];
        
        DefaultTableModel modelo =  new DefaultTableModel(null, titulos);
        
        
        try{
            CallableStatement consulta = con.prepareCall("{call consulta_buscar("+txtBuscar.getText()+")}");
            ResultSet rs = consulta.executeQuery();
            
            while(rs.next()){
                registros[0] = rs.getString("id");
                registros[1] = rs.getString("nombre");
                registros[2] = rs.getString("apellido1");
                registros[3] = rs.getString("apellido2");
                registros[4] = rs.getString("tipo_documento");
                registros[5] = rs.getString("numero_documento");
                registros[6] = rs.getString("email");
                registros[7] = rs.getString("numero_celular");
                registros[8] = rs.getString("codigo");
                
                modelo.addRow(registros);
            }
            DataTable.setModel(modelo);
            rs.close();
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,"Error " + e.getMessage());
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmTablaDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmTablaDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmTablaDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmTablaDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmTablaDatos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable DataTable;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtBuscar;
    // End of variables declaration//GEN-END:variables
}
